enabled: false
ldapHost: "ldap.home.pvt"
ldapPort: 389
use_tls: false
bindDN: ""
userSearchBase: ""
userNameAttribute: "uid"
userMailAttribute: "mail"
userObjectClass: "person"
groupSearchBase: ""
groupAttribute: "member"
groupObjectClass: "group"
origin: ldap
insecure_skip_verify: ""
ca_cert: ""
useIDForSAMLUser: false
minTLSVersion: "1.0"
maxTLSVersion: "1.3"
